[tool.ruff]
line-length = 88
extend-select = ["I"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.pytest.ini_options]
pythonpath = [".", "src"]