[thermoino]
port = "COM12" # COM7 for Luigi, COM12 for Mario
mms_baseline = 28.0  # must be the same as in MMS
mms_rate_of_rise = 10.0  # must be the same as in MMS

[experiment]
text_size = 40
text_box_size = [1500, 900]
element_color = [128, 64, 192]
cross_pain_color = [192, 64, 128]
cross_size = [100, 100]
cross_line_width = 20

[stimulus]
stimulus_duration = 8000
iti_duration = 8000
iti_max_jitter = 3000
iti_duration_short = 1000
preexposure_temperatures = [35.0, 36.0, 37.0]
preexposure_correction = 2.0  # we subtract this from the vas70 estimate if preexposure was painful

[estimator]
# VAS 70
trials_vas70 = 7
temp_start_vas70 = 42.0
temp_std_vas70 = 3.5
# VAS 0
trials_vas0 = 5
temp_start_vas0 = inf  # will be set after VAS 70 estimate
temp_start_vas0_offset = 3.0  # vas0 = vas70 - offset
temp_std_vas0 = 1.5

[dummy_participant]
id = "dummy"
age = 20
gender = "Female"
