[experiment]
text_size = 40
text_box_size = [1500, 900] 
element_color = [128, 64, 192]
marker_color = [192, 64, 128]

[visual_analogue_scale]
sample_rate = 60
bar_length = 800
bar_thickness = 20
bar_position = [0, 0]
slider_width = 10
slider_height = 60
slider_color = [194, 24, 7]
label_text_size = 40
label_text_box_size = [250, 100]

[stimulus]
seeds = [786, 539, 589, 869, 431, 340, 395, 211, 909, 827, 405, 119]
half_cycle_num = 10
sample_rate = 10
period_range = [5, 20]
amplitude_range = [0.1, 0.9]
median_range = 0.3
big_decreasing_half_cycle_num = 3
big_decreasing_half_cycle_period = 20
big_decreasing_half_cycle_amplitude = 0.85
plateau_num = 3
plateau_duration = 20
plateau_percentile_range = [25, 75]

[imotions]
sample_rate = 10
start_study_mode = "NormalPrompt"

[dummy_participant]
time_stamp = "2024-01-01 15:00:00"
id = "dummy"
age = 20
gender = "Female"
temperature_baseline = 40.0
temperature_range = 3
