[thermoino]
port = "COM12"  # COM7 for Luigi, COM12 for Mario
mms_baseline = 28.0  # must be the same as in MMS
mms_rate_of_rise = 10  # must be the same as in MMS
bin_size_ms = 500

[experiment]
text_size = 40
text_box_size = [1500, 900] 
element_color = [128, 64, 192]
marker_color = [192, 64, 128]

[visual_analogue_scale]
sample_rate = 60
bar_length = 800
bar_thickness = 20
bar_position = [0, 0]
slider_width = 10
slider_height = 60
slider_color = [194, 24, 7]
label_text_size = 40
label_text_box_size = [250, 100]

[stimulus]
seeds = [43, 242, 320, 43, 242, 320, 43, 242, 320, 43, 242]
minimal_desired_duration = 200
periods = [67, 20]  # periods are easier to handle than frequencies
sample_rate = 5
desired_big_decreases = [3, 20]
random_periods = true
plateau_duration = 20
n_plateaus = 3

[imotions]
sample_rate = 10
start_study_mode = "NormalPrompt"

[dummy_participant]
time_stamp = "2024-01-01 15:00:00"
id = "dummy"
age = 20
gender = "Female"
temp_range = 3
baseline_temp = 40.0
